### ISSUE TITLE
IOS 13: Can not select Instagram app

### ISSUE THREAD

**Issue by rjlinden** [vstirbu/InstagramPlugin#111]
Hello,

We are not able to select the instagram app on ios 13 after we call the share functionality.
Do you have any idea why or how we can fix this?

Cheers,
Roberto

**Comment by paulwalczewski** [comment]
Experiening same issue here :/

**Comment by jk90-obi** [comment]
I also have the same issue, would be great if it could be fixed @vstirbu . Thanks!

**Comment by chase-wen-hs** [comment]
Same issue in iOS 13

**Comment by vstirbu** [comment]
need a pair of eyes to review #106

**Comment by chase-wen-hs** [comment]
> need a pair of eyes to review #106

Hi, I am from the same group as this PR owner. Please close this PR as it is no longer valid now.

This PR was requested one year ago and it is not for the purpose of this ios 13 fix. Since g4-KN is no longer working at the company, so please help to close this PR.

Besides, I think replacing instagram.igo with image is a workaround for the iOS 13 transition, it shouldn't be a official fix for the plugin

**Comment by bally86** [comment]
> 
> 
> > need a pair of eyes to review #106
> 
> Hi, I am from the same group as this PR owner. Please close this PR as it is no longer valid now.
> 
> This PR was requested one year ago and it is not for the purpose of this ios 13 fix. Since g4-KN is no longer working at the company, so please help to close this PR.
> 
> Besides, I think replacing instagram.igo with image is only a workaround for the iOS 13 transition, it shouldn't be an official fix for this plugin

So can you explain what we need to do to get it working on IOS13 again?

**Comment by jk90-obi** [comment]
Any news on a fix? More users are upgrading to iOs13, so we get more complaints. Thanks!

**Comment by msigwart** [comment]
Just tried out the fix in #112, worked for me! Just remember to `cordova rm ios` and `cordova add ios` again.

**Comment by jk90-obi** [comment]
Now we need someone with write access to review & approve the PR

**Comment by roxteddy** [comment]
I've even seen an app that opens directly Instagram without goin thru ios app picker. I wonder how they do this..

**Comment by albertleao** [comment]
Bump... still broken! :(

**Comment by joehui** [comment]
Tried #112 but it is not working for me.  After picking instagram app (which was hidden under the "More" button), it didn't launch Instagram app, and then my app locked up.

**Comment by rodrigograca31** [comment]
This should be fixed.

But seems theres an issue again on iOS 13.6.1 ....
