### ISSUE TITLE
Unable to load image for FEED

### ISSUE THREAD

**Issue by mblint-postcron** [vstirbu/InstagramPlugin#113]
I'm facing an issue sending a share intent to Instagram on Android, from the last update from 3 days ago. This is on an Ionic app

I can reproduce the error in the following conditions:

Android >= 8
Last Instagram Version (133.0.0.32.120)
Only sharing to Feed, Stories read the image as expected

I will not add the code I'm using to share because seems to be another thing, some change that Instagram introduced in the last update, maybe permissions or something else.

I discard the image path (read/write) because for Stories it's working fine.

Any ideas? Thanks.

**Comment by hdeshmukh** [comment]
Same here.
Android >=8
Instagram Version (133.0.0.32.120)
Sharing to feeds, direct fails.  Debugging the issue it looks like the error message returned is ShareCancelled

![image](https://user-images.githubusercontent.com/3018663/77187430-b3f1ec80-6a91-11ea-993a-8d6d895b73c3.png)

This all happened when Instagram updated to their latest version

**Comment by souvenirpixels** [comment]
Same issue here, was working fine before Instagram version 133.0.0.32.120.  Instagram shows message "Unable to load image"  then kicks out. Same error as @hdeshmukh, any ideas how to troubleshoot this one?

**Comment by mblint-postcron** [comment]
Hello guys. I'm trying to fix this issue but not lucky yet. I could say that tried with different images, sizes, dimensions, and formats, and all fails the same. So the problem should be related to anything else, maybe permissions.

This is weird because Stories work like a charm :/

**Comment by hdeshmukh** [comment]
Weird thing is I cannot reproduce the issue on Android 6.  Everything seems to be working fine on an older device.

**Comment by mblint-postcron** [comment]
Yes, meanwhile email to android-support@instagram.com, maybe we get their attention

**Comment by souvenirpixels** [comment]
I emailed them as well, if I get any useful feedback will post back to this thread.

**Comment by mblint-postcron** [comment]
@souvenirpixels @hdeshmukh hello guys! IG just release a new version for Android, could you check if is working now for you or still have the issue? Thanks

**Comment by souvenirpixels** [comment]
Just checked, still not working with the new version (134.0.0.26.121), also haven't gotten any response from Instagram yet.

**Comment by mblint-postcron** [comment]
Hello guys @souvenirpixels @hdeshmukh, there is a ticket on Facebook bugs section: https://developers.facebook.com/support/bugs/1326888287510350/

Can you leave a message there?
Thanks

**Comment by souvenirpixels** [comment]
Thanks, I left a message and following the thread.  There is also a slackoverflow thread that suggests a work around may be writing to the media store then posting from there will work.  

https://stackoverflow.com/questions/60786976/share-intent-issue-in-instagram-feed

Haven't been able to confirm if this is a possible fix.

**Comment by mblint-postcron** [comment]
Thanks! I will try to do the same workaround in Java, but i'm a frontend developer há please add information here if you have

**Comment by mauriblint** [comment]
Workaround solution to fix temporary this IG bug (I think is a bug from the Instagram app)
https://stackoverflow.com/questions/60776730/instagram-android-share-intent-unable-to-load-image

**Comment by rodrigograca31** [comment]
Can confirm this problem.
This explains the increase in installs and uninstalls of my app... (probably all apps are broken)

Instagram version: 134.0.0.26.1
Android 9

**Comment by luarfaria** [comment]
It was a prolem with instagram app, other applications as whatsapp also had the same problem. After some weeks, i tested and share function is working.

**Comment by rodrigograca31** [comment]
Yeah, its working again.
