### ISSUE TITLE
[Suggestion] - Option to set share type

### ISSUE THREAD

**Issue by Piket564** [vstirbu/InstagramPlugin#116]
Hi all, i'm building a personal app with Ionic
```
Ionic:

   Ionic CLI                     : 6.11.8 
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 16 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0
```

It's possible with this plugin, share directly in a stories?
Like Spotify do?

Thanks a lot!

**Comment by rodrigograca31** [comment]
Directly?

It does show the 3 options right?
Stories, feed, and something else that I cant remember...

**Comment by Piket564** [comment]
In iOs it works as a normal Share, on Samsung S10 (Android 10) it works as Instagram only share, but it ask for what you want to share.

I'd like to use like Spotify Share.
Directly into stories.

**Comment by rodrigograca31** [comment]
I'm confused. if you intend to share on Spotify this is not the correct plugin....
