### ISSUE TITLE
Android API 30 - Instagram not installed 

### ISSUE THREAD

**Issue by dharmikp95** [vstirbu/InstagramPlugin#121]
-Plugin working in API 29
-After updating API level to 30 plugin stop working in android(no issues in IOS)

**Comment by dharmikp95** [comment]
Instagram.isInstalled no longer work in android 11
https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by rodrigograca31** [comment]
🤔🤔

So if you target 11 it cannot see instagram installed? if I remember correctly you have to justify your use to the store to let it see it, right?

**Comment by dharmikp95** [comment]
> 🤔🤔
> 
> So if you target 11 it cannot see instagram installed? if I remember correctly you have to justify your use to the store to let it see it, right?

Yes

**Comment by rodrigograca31** [comment]
Then, sorry to say but I think "thats your problem" not the plugins problem.
