### ISSUE TITLE
Instagram Login

### ISSUE THREAD

**Issue by micheltobon** [vstirbu/InstagramPlugin#27]
Hello Vlad, I am wondering if it is possible to extend your excellent plugin (congratulations BTW) to do 2 things:

1: Send a text message to Instagram so that the user already has some default text to publish and 
2: Login to Instagram via the active session on the mobile device (like all applications do with facebook)

I hope you can help me with this, best regards!

**Comment by benjick** [comment]
Isn't this possible now in Android? I see SquarePic inserts a hashtag and mention to their app whenever used on Android
