### ISSUE TITLE
Facebook app appears in list

### ISSUE THREAD

**Issue by hannahcin** [vstirbu/InstagramPlugin#34]
Hi there,

iPhone 6, iOS 8.3

We've found that when the Facebook app is installed, the app appears in the share list. This is problematic since there is much overlap in our users who have both Instagram and Facebook installed on their phones.

![image](https://cloud.githubusercontent.com/assets/8988510/7354098/963b3788-eccd-11e4-909a-da2a3bb483cc.png)

**Comment by vstirbu** [comment]
Seems to be the same as #23

**Comment by hannahcin** [comment]
Yes... Facebook is more problematic though, since many Instagram users overlap with Facebook users. Any way this can be looked into?

**Comment by vstirbu** [comment]
Not from the app that shares the image. The plugin is fully compliant with Instagram's developer [documentation](https://instagram.com/developer/mobile-sharing/iphone-hooks/) but is seems that now even Facebook does not follow that recommendation... :(

**Comment by vstirbu** [comment]
I'll close the issue as currently there is not technical solution for this.
