### ISSUE TITLE
Crops when installed from Google Play

### ISSUE THREAD

**Issue by rogercrandall** [vstirbu/InstagramPlugin#35]
The plugin works great when testing my app. Now I have the app live on the Google play store and when it is installed from there, it crops the images in half. Only showing the top half of the image. Any thoughts on why this would be happening?

**Comment by vstirbu** [comment]
anyone else experiencing this behaviour?

**Comment by rodrigograca31** [comment]
I a related problem, it was not because of this plugin...
It was because of the way I was picking the image, the plugin I was using was making a temporary copy, than deleted it, because of that if the phone took a bit more time the image would be deleted and sometimes my app would only get half of it...

**Comment by vstirbu** [comment]
Thanks for sharing this information here!

The plugin does not delete the image till next time a image is shared, so this could not be the reason of getting the half image in our case.

**Comment by kunalnagar** [comment]
@vstirbu I'm facing a similar issue on iOS. Here it is:

When I send an image to Instagram via a cordova app, I don't get the pan-around option (in Instagram) that will allow me to select part of the image. Instead, it just crops part of the image and displays it (not sure how that is happening either).

**Comment by vstirbu** [comment]
@kunalnagar You could get more exposure if you open a new issue as your situation is not the same as on this topic.

**Comment by kunalnagar** [comment]
@vstirbu #41

**Comment by vstirbu** [comment]
reopen if still an issue
