### ISSUE TITLE
jpg to Base64 dont work

### ISSUE THREAD

**Issue by zhock** [vstirbu/InstagramPlugin#37]
After struggling so long, i finally found the solution! my photos .jpg(like https://farm9.static.flickr.com/8774/17224261904_3608efc466_z.jpg) converted in base64 through PHP and than changed into InstagramPlugin with Ajax. 

Problem: .jpg base64 photos can't be shared on instagram.

Solution: i changed them into data:images/png (data:image/png;base64,/9j/4AAQSkZJ...) in order to fool instagram and make it work.

**Comment by waholleyiv** [comment]
I don't understand what your problem nor solution was; Can you clarify?

**Comment by vstirbu** [comment]
@zhock Are you getting the image from an external service?
