### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by daksamedia** [vstirbu/InstagramPlugin#42]
How to authenticate login use Instagram API?

**Comment by micheltobon** [comment]
What I use in this case is login via open graph by using an inapp browser

**Comment by daksamedia** [comment]
do you have a sample for this case ??

**Comment by vstirbu** [comment]
The purpose of this plugin is to share the image via the native Instagram application (iOS or Android), and _not_ via the Instagram HTTP API.

There is a discussion about login in to Instagram via the HTTP API on the [chat channel](https://gitter.im/vstirbu/InstagramPlugin). Scroll to the beginning.

**Comment by daksamedia** [comment]
Please kindly reply message on that site. Thank you :) @vstirbu

**Comment by micheltobon** [comment]
@daksamedia  Yes, I have an example:

```
/*
BASED ON
 https://github.com/caiovaccaro/phonegap.facebook.inappbrowser
 */
(function() {

    InstagramInAppBrowser = {
        settings: {
            redirectUrl: ''
        }
        , login: function(successCallback, finalCallback) {

            var authorize_url = baseURL + "igLogin.php";

            var instaView,
                    callback = function(location) {

                        if (location.url.indexOf("access_token") !== -1) {
                            var access_token = location.url.match(/access_token=(.*)$/)[1].split('&exit=1')[0];
                            window.localStorage.setItem('IGaccessToken', access_token);
                            instaView.close();

                            if (typeof successCallback !== 'undefined' && typeof successCallback === 'function') {
                                window.localStorage.setItem('ig_connected',true);
                                successCallback();
                            }

                        }

                        if (location.url.indexOf("error_reason=user_denied") !== -1) {
                            window.localStorage.setItem('ig_connected',false);
                            userDenied = true;
                            instaView.close();
                        }
                    },
                    userDenied = false;

            instaView = window.open(authorize_url, '_blank', 'location=no');
            instaView.addEventListener('loadstart', callback);
            instaView.addEventListener('exit', function() {

                if (window.localStorage.getItem('IGaccessToken') === null && userDenied === false) {
                    if (typeof finalCallback !== 'undefined' && typeof finalCallback === 'function') {
                        finalCallback();
                    }

                }

                userDenied = false;

            });

        }

    };

}).call(this);

```

**Comment by micheltobon** [comment]
you  include this element in a new JS file, then you call it and add the proper events and return functions, it's quite simple, actually

**Comment by daksamedia** [comment]
How do I include client key, secret key & scope??

**Comment by micheltobon** [comment]
you have to go to the instagram developer page and register your application

**Comment by daksamedia** [comment]
where do I put those keys in?

**Comment by daksamedia** [comment]
@micheltobon could you tell me where should I put my client key, permission, etc with your source code?

**Comment by micheltobon** [comment]
@daksamedia sorry for the late reponse.
Here is the situation, as you can see in line 12 (var authorize_url = baseURL + "igLogin.php";)
here is where we send the user to OUR server, to a script called idLogin.php so the variable baseURL must be changed for the name of your server (www.myserver.com/igLogin.php 

in the igLogin.php file I do a few things:

1. check if the $_GET is empty
2. if the $_GET is empty redirect him to the instagram login page
3. ELSE IF the $_GET variable access_token you can terminate your script, therefore your login is complete, later on you will have to use the access token you have received to start getting the user's data and everything you need, SO...

```
<?php 
if (!sizeof($_GET)) {

    //DIRECT THE USER TO THE LOGIN AREA IN INSTAGRAM
    $URL = "https://api.instagram.com/oauth/authorize/?client_id=[INSTAGRAM_CLIENT_ID]&";
    $URL .= "redirect_uri=[HTTP://WWW:YOURWEBSITE,COM/]igLogin.php&";
    $URL .= "response_type=code&";
    //OPTIONAL FOR THE PERMISSIONS YOU WANT TO USE
    $URL .= "scope=comments";

    header('location:' . $URL);
} else {  
     //either do something with the data provided in the URL or you can just receive the access token via the URL in the inappbrowser and do something via javascript or whatevaaaa
}
?>
```

**Comment by daksamedia** [comment]
As you can see on your source (Line 9) - first source - 
Do I need to fill the blank for redirect URL?

**Comment by micheltobon** [comment]
no, not really... it's not used in this case, because you are using the redirection to the PHP file

**Comment by daksamedia** [comment]
I'll try this one.
Is it true, if I just add this on html?
<button="login-ig" onclick=" InstagramInAppBrowser.login();">LOGIN VIA INSTAGRAM</button>

**Comment by micheltobon** [comment]
well yes, but the right way to call it is with a callback function, something like this:
```
<button onclick="InstagramInAppBrowser.login(function(successResponse){
console.log(successResponse);
alert('The user has logged in');
},function(failureResponse){
console.log(successResponse);
alert('The was an error in the login);
})"
```

**Comment by daksamedia** [comment]
is this works on your app?

**Comment by micheltobon** [comment]
of course... 100%
