### ISSUE TITLE
 CordovaPlugin: Attempted to send a second callback for ID: Instagram612896362

### ISSUE THREAD

**Issue by pranaydutta89** [vstirbu/InstagramPlugin#43]
if i run the plugin in a demo app(the share function) it works , but when i integrate to the original its not showing any action ,neither error nor success(in share function) but t he isInstalled function is getting called and working correct, and in debug log i am getting this error

08-07 11:51:09.210 25214 25316 W CordovaPlugin: Attempted to send a second callback for ID: Instagram612896362
08-07 11:51:09.210 25214 25316 W CordovaPlugin: Result was: "Invalid action"

please help me with this one

**Comment by vstirbu** [comment]
Pretty hard to see what goes wrong without seeing some code... Can you try to reproduce the problem extending the example app?

**Comment by pranaydutta89** [comment]
well thanx for the comment  , however the problem was something different i was  truncating the data:image/png part by a regex and after inspecting your code found that you where also doing the same thing, now Instagram app is opening up, but it's only sharing part of image ,not the full image can you please help me with this

**Comment by vstirbu** [comment]
can you post a screen capture? it might be similar to #35.

**Comment by pranaydutta89** [comment]
i found the problem  now i am able to share the whole image if image is in png format for jpeg its truncating the image,and the callback is also not working it always gives me as shared failed

**Comment by vstirbu** [comment]
Thanks for the update. I'll update the documentation to indicate that the image should be in png format.

It was already noted in another issue that on Android the Instagram application does not report if the action was successful.

**Comment by pranaydutta89** [comment]
if possible can you please keep as a promise sort of callback

**Comment by vstirbu** [comment]
If you use angular/ionic, you can fins a wrapper in [ngcordova](http://ngcordova.com/docs/plugins/instagram/).

**Comment by pranaydutta89** [comment]
i used it its giving me CDEP error,there is some bug with ngcordova anyways thanx for reply
