### ISSUE TITLE
The caption is not working with the latest Instagram version....

### ISSUE THREAD

**Issue by rodrigograca31** [vstirbu/InstagramPlugin#44]
Maybe something change... and I noticed that the caption was not working...

Steps:

```bash
ionic start myApp222 blank
cd myApp222/
ionic platforms add android
cordova plugin add cordova-instagram-plugin
```
Add the following code inside `$ionicPlatform.ready(function() {`

```javascript
Instagram.share("canvas", "hey!", function (err) {
    if (err) {
        console.log("not shared");
    } else {
        console.log("shared");
    }
```
and
```html
<canvas id="canvas" width="5" height="5"></canvas>
```
inside `<ion-content></ion-content>`

Then do: `ionic run`

Share it on Instagram and notice that the "hey!" string is not there....

Thanks for the plugin/help!

**Comment by vstirbu** [comment]
Yep, expected issue... Caption on Android uses an undocumented feature, so we are the mercy of Instagram to keep it or not. :(

**Comment by rodrigograca31** [comment]
:disappointed_relieved: 
Any way that this can be fixed?
Can I help in any way?

**Comment by vstirbu** [comment]
Not that I'm aware of. The plugin sets the caption text in the [intent](https://github.com/vstirbu/InstagramPlugin/blob/master/src/android/CDVInstagramPlugin.java#L118), but the value is ignored by the Instagram application.

**Comment by rodrigograca31** [comment]
"Removing pre-filled captions from mobile sharing" http://developers.instagram.com/post/125972775561/removing-pre-filled-captions-from-mobile-sharing

They broke half of my App.... Not cool! ;(

**Comment by vstirbu** [comment]
there is an interesting approach tried [here](https://github.com/seanconormcdonnell/InstagramPlugin/commit/43b9bab1cd25cb495aabf87fa856a2cd48b2d7fc), although I'm concerned about the usability...

**Comment by rodrigograca31** [comment]
Oh.... I forgot to post this here... I thought about doing that and then saw an application doing it:
![](http://i.stack.imgur.com/LLZkj.jpg)

**Comment by manuelpaulo** [comment]
"This is a non-breaking change: existing mobile apps that utilize pre-filled captions will continue to be able to use this flow to share media through the Instagram apps"

What does this means? Can we update the app, as long as it's the same app_id?

**Comment by rodrigograca31** [comment]
If you read the rest... "but now Instagram will ignore the caption text."

In other words, you can send them the caption, they will ignore it and not error will be displayed....

**Comment by manuelpaulo** [comment]
I have just updated the Instagram app and it works as expected on my app that I have updated last week... (sharing images only)
