### ISSUE TITLE
Copy caption to clipboard

### ISSUE THREAD

**Issue by seanconormcdonnell** [vstirbu/InstagramPlugin#45]
as outlined in <a href="http://developers.instagram.com/post/125972775561/removing-pre-filled-captions-from-mobile-sharing">this</a> blog post Instagram no longer excepts pre-filled captions. While the plug in is still working as is, it could be improved with a copy/paste function. I have forked this repository and edited it so now the caption is copied to the clip board. However I am not familiar enough with objective-c to say that I have done this the best way, I am not even sure if this is the best way to handle this.

**Comment by vstirbu** [comment]
There are apps that use this technique to overcome the change in behaviour of Instagram app (see an example in #44 ). Would it be of interest to add this feature to the plugin.

Obviously the user interface side of how to instruct the users of your app to paste the caption in Instagram is out of scope. Basically, the plugin just copies the caption and we can use `share` with three arguments for it.

**Comment by rodrigograca31** [comment]
> Basically, the plugin just copies the caption and we can use share with three arguments for it.

Good idea! :+1:

**Comment by rodrigograca31** [comment]
I've used this plugin for copying to the clipboard: https://github.com/VersoSolutions/CordovaClipboard

**Comment by vstirbu** [comment]
Thanks for the pointer. Suits perfectly our needs.
