### ISSUE TITLE
iOS 9

### ISSUE THREAD

**Issue by ErikAugust** [vstirbu/InstagramPlugin#47]
Looks to not be available in iOS9 - any ideas? Thanks.

**Comment by yodarjun** [comment]
+1 Has anyone been able to get this working in iOS9? It works perfectly in 8.4. Any help would be much appreciated. Thanks.

**Comment by sfrdmn** [comment]
It should work. iOS 9 changed how custom URL are handled: you need to explicitly white list custom URLs e.g. `instagram://` for this plugin to work

You can modify your `*-Info.plist` file in `/platforms/ios`, but that's a generated file. Alternatively, I think you can make a custom plugin which generates the correct values in the .plist file

See [link](http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes)

**Comment by vstirbu** [comment]
We can handle this from within this plugin by adding a [config-file](http://cordova.apache.org/docs/en/5.0.0/plugin_ref_spec.md.html#Plugin%20Specification) element in the iOS section of the [plugin.xml](https://github.com/vstirbu/InstagramPlugin/blob/master/plugin.xml#L39).

```
<config-file target="*-Info.plist" parent="CFBundleURLTypes">
    <array>
        <dict>
            <key>key</key>
            <string>value</string>
        </dict>
    </array>
</config-file>
```
We just need the relevant key and value.

**Comment by sfrdmn** [comment]
Oh right :P 

This works for me:
```xml
<platform name="ios">
  <config-file target="*-Info.plist" parent="LSApplicationQueriesSchemes">
    <array>
      <string>instagram</string>
    </array>
  </config-file>
</platform>
```

**Comment by sfrdmn** [comment]
However, previous values in `LSApplicationQueriesSchemes` should not be overwritten. Not sure how to do that.

**Comment by vstirbu** [comment]
Looking at plugman source code, and it seems that when the plist is updated all values are merged instead of overwritten. So, I would say that just adding the snippet to the plugin.xml is the right thing to do to fix the functionality for iOS9.

@sfrdmn, would you make a pull request?
