### ISSUE TITLE
include caption

### ISSUE THREAD

**Issue by leonardofrmello** [vstirbu/InstagramPlugin#53]
It has possibility to include caption?

My code, i use var caption and it was not possible

 function shareOnInstagram(){
            var caption = "RioMar Natal"
            Instagram.share('canvasDrawImage', caption, function (err) {
                if (err) {
                    //alert(err);
                } else {
                    //alert('imagem compartilhada com sucesso');
                }
            });
        }

**Comment by vstirbu** [comment]
Cannot be done. Instagram removed that feature from their apps. More details here: http://developers.instagram.com/post/125972775561/removing-pre-filled-captions-from-mobile-sharing.
