### ISSUE TITLE
Error: undefined is not an object (evaluating 'data.slice')

### ISSUE THREAD

**Issue by ilgianfra** [vstirbu/InstagramPlugin#55]
I want to share one image in my file system (file:///var/mobile/Containers/Data/Application/88F85219-C19E-452D-B5F0-11D9438DF5E5/Library/NoCloud/1453894916583.jpg)
then I call:
`$cordovaInstagram.share(getBase64Image(index), null)
`
the function getBase64Image:
```
    function getBase64Image(index) {
      var ccc = "base64" + index
      console.log('BASE64', ccc);
      var img = document.getElementById(ccc);
      console.log('IMG', img);
      var canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      var ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      
      var dataURL = canvas.toDataURL();
      console.log(dataURL);
      return dataURL;
    }
```

My console.log of dataURL looks like a real base64 image but I still get this error:

> Error: undefined is not an object (evaluating 'data.slice')
> share@file:///var/mobile/Containers/Bundle/Application/640C9E51-2DE8-4DF0-A1BF-EBC99C1E63E7/alpitour.app/www/plugins/cordova-instagram-plugin/www/CDVInstagramPlugin.js:92:18
> share@file:///var/mobile/Containers/Bundle/Application/640C9E51-2DE8-4DF0-A1BF-EBC99C1E63E7/alpitour.app/www/lib/ngCordova/dist/ng-cordova.min.js:8:24663

Am I missing something ?

**Comment by vstirbu** [comment]
You are actually calling the `share` from ng-cordova [instagram plugin](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/instagram.js#L10). Try like this:

```
$cordovaInstagram.share({
   image: getBase64Image(index)
});
```

**Comment by ilgianfra** [comment]
Thank you!
