### ISSUE TITLE
No know class method for selector error

### ISSUE THREAD

**Issue by softBarbarian** [vstirbu/InstagramPlugin#56]
i am running cordova-ios 4.0.1 and when this plugin is added it throws following error:
```
platforms/ios/Frockhub/Plugins/cordova-instagram-plugin/CDVInstagramPlugin/CDVInstagramPlugin.m:63:36: error: no known class method for selector 'dataFromBase64String:'
        NSData *imageObj = [NSData dataFromBase64String:objectAtIndex0];
                                   ^~~~~~~~~~~~~~~~~~~~
1 error generated.

```
here is my info:
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.4 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by vstirbu** [comment]
When using the plugin in an ionic/angular application you have to use the corresponding ng-cordova plugin. Check #55 to see if you are in the same situation. If not, could you share the code where you use the plugin.

**Comment by funkjedi** [comment]
Just posted a pull request with a fix that worked for me. Apparently `dataFromBase64String` was deprecated in `3.8.0` and removed in `4.x.x`.

**Comment by softBarbarian** [comment]
@funkjedi NICE!!!!!!!
