### ISSUE TITLE
Not working on android 6

### ISSUE THREAD

**Issue by jordiv3d** [vstirbu/InstagramPlugin#59]
Hi, I have succedfully integrated the plugin on android, and tested on android 5 where it's working ok, bit not on a nexus5 running android 6, is there any known workaround ?
Thanks in advance

**Comment by vstirbu** [comment]
Can you provide more details? Thanks!

**Comment by jordiv3d** [comment]
Sorry, it was my fault, as I uninstalled instagram first, and then I did not open it once reinstalled, so I haven't the permit to access images from instagram.

**Comment by vstirbu** [comment]
so, it is working? can the issue be closed?

**Comment by jordiv3d** [comment]
Yes , it's working so can be closed. Thanks for that great plugin !!
