### ISSUE TITLE
Improve performance - AsynTask - Android

### ISSUE THREAD

**Issue by rodrigograca31** [vstirbu/InstagramPlugin#62]
The base64 decode is a bit slow....
I'm not and expert in Java, but I think this plugin could/should use an AsynTask...

[https://www.youtube.com/watch?v=jtlRNNhane0](https://www.youtube.com/watch?v=jtlRNNhane0)

**What's your opinion?**

**Comment by vstirbu** [comment]
could provide a slight improvement, although the main bottleneck in this case is transferring the base64 encoded string from the webview to native. worth experimenting...

**Comment by rodrigograca31** [comment]
@vstirbu You are saying that the "slowness" I'm experiencing is in the mostly in the transfer process?

**Comment by vstirbu** [comment]
this is a relevant discussion: http://stackoverflow.com/questions/35875828/determining-throughput-speed-cordova-bridge-any-insights. the question is iOS specific but still relevant...

**Comment by rodrigograca31** [comment]
I tried something similar to that in the past...
I basically printed a bunch of timestamps to the Android logcat to find where it was taking most of the time....

**Comment by vstirbu** [comment]
can you instrument this [line](https://github.com/vstirbu/InstagramPlugin/blob/master/src/android/CDVInstagramPlugin.java#L88) to see what is the delay on decoding the base64 image?

**Comment by rodrigograca31** [comment]
Not right now, but I can do it later or this weekend....

**Comment by rodrigograca31** [comment]
I've made the following modification to the library:
```java
    private void share(String imageString, String captionString) {
        if (imageString != null && imageString.length() > 0) { 
Long tsLong = System.currentTimeMillis()/1000;
Log.d("Base64", tsLong.toString());
        	byte[] imageData = Base64.decode(imageString, 0);
tsLong = System.currentTimeMillis()/1000;
Log.d("Base64", tsLong.toString());
        	File file = null;  
            FileOutputStream os = null;
        	
        	File parentDir = this.webView.getContext().getExternalFilesDir(null);
            File[] oldImages = parentDir.listFiles(OLD_IMAGE_FILTER);
            for (File oldImage : oldImages) {
                oldImage.delete();
            }
tsLong = System.currentTimeMillis()/1000;
Log.d("createTempFile", tsLong.toString());
            try {
                file = File.createTempFile("instagram", ".png", parentDir);
                os = new FileOutputStream(file, true);
            } catch (Exception e) {
                e.printStackTrace();
            }
tsLong = System.currentTimeMillis()/1000;
Log.d("createTempFile", tsLong.toString());
tsLong = System.currentTimeMillis()/1000;
Log.d("write", tsLong.toString());
        	try {
        		os.write(imageData);
				os.flush();
				os.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
tsLong = System.currentTimeMillis()/1000;
Log.d("write", tsLong.toString());
tsLong = System.currentTimeMillis()/1000;
Log.d("shareIntent", tsLong.toString());
        	Intent shareIntent = new Intent(Intent.ACTION_SEND);
        	shareIntent.setType("image/*");
        	shareIntent.putExtra(Intent.EXTRA_STREAM, Uri.parse("file://" + file));
        	shareIntent.putExtra(Intent.EXTRA_TEXT, captionString);
        	shareIntent.setPackage("com.instagram.android");
        	
        	this.cordova.startActivityForResult((CordovaPlugin) this, shareIntent, 12345);
tsLong = System.currentTimeMillis()/1000;
Log.d("shareIntent", tsLong.toString());
        	
        } else {
            this.cbContext.error("Expected one non-empty string argument.");
        }
    }
```
(added `tsLong` and `Log.d`)
Result:
```
03-19 14:36:09.911 24625-24691/APP D/Base64: 1458398169
03-19 14:36:09.951 24625-24691/APP D/Base64: 1458398169
03-19 14:36:09.961 24625-24691/APP D/createTempFile: 1458398169
03-19 14:36:09.961 24625-24691/APP D/createTempFile: 1458398169
03-19 14:36:09.961 24625-24691/APP D/write: 1458398169
03-19 14:36:09.971 24625-24691/APP D/write: 1458398169
03-19 14:36:09.971 24625-24691/APP D/shareIntent: 1458398169
03-19 14:36:09.991 24625-24691/APP D/shareIntent: 1458398170
```

I've also added some logging to the javascript (before and after calling the library):
```
Instagram 1458398169.349
Instagram 1458398170.008
```

Conclusion: This timings are actually good (1 sec), but:

1. They are from my OnePlus One (good phone)
2. Testing on a clean Moto G (1st gen) also took about 1 second.
3. Testing with a 1000 x 1000 canvas in the Moto G is also acceptable.
4. I think this good timings have to do with me using 5.1.1 (because Google Warned developer to update the cordova version), I'm saying this because some months ago this library would take 2-3 seconds or more to process.... 

That said, there's always room for improvement, and using `AsynTask` would probably make it even faster...
