### ISSUE TITLE
Caption does not enter clipboard android 4.4.2

### ISSUE THREAD

**Issue by Bart-Holland** [vstirbu/InstagramPlugin#63]
So I am using Android 4.4.2 with the latest cordova and the latest instragram app.
In my app I take a picture and then add this to instagram using Instagram.share();

Of course I also would like to set a capture and looking into the readme file I would expext that I can paste the caption from the clipboard. However the data does not seem to enter the clipboard.
Might just be that I am doing something wrong. So just to be sure here is my code:

```
    cameraSuccess: function (attr) {

        window.resolveLocalFileSystemURL(attr, function (fileEntry) {

            fileEntry.file(function(file) {

                var reader = new FileReader();
                var caption = "TEST CAPTION!";
                
                reader.onloadend = function(e) {
                   
                    Instagram.share(this.result, caption, function (err) {

                        /*
                        if (err) {
                            alert('Not shared on instagram');
                        } else {
                            alert("shared!");
                        }
                        */
                    });

                };
                reader.readAsDataURL(file);
            });

        }, function(err) {
            //alert(err);
        });

    },
```

So is this the way it supposed to work or am I just mis using the script here?

**Comment by vstirbu** [comment]
We are using an [external plugin](https://github.com/Visigo/CordovaClipboard) for [copying](https://github.com/vstirbu/InstagramPlugin/blob/master/www/CDVInstagramPlugin.js#L35) to clipboard.

The use of share seem right although I'm not sure where `this.result` is coming from.

**Comment by vstirbu** [comment]
Can you check what version of CordovaClipboard plugin is installed by cordova-cli?

**Comment by Bart-Holland** [comment]
this.result is comming from the solution entered here: 
https://github.com/vstirbu/InstagramPlugin/issues/29

**Comment by vstirbu** [comment]
Can you add a success and error callback [here](https://github.com/vstirbu/InstagramPlugin/blob/master/www/CDVInstagramPlugin.js#L35) to see what is going on there?

**Comment by Bart-Holland** [comment]
I just downloaded the latest clipboard plugin, seems tge build is faling on the clipboard plugin.
Will have a look at the callback. though instagram seems always to return an error...

**Comment by Bart-Holland** [comment]
Did a new download:

cordova plugin add https://github.com/VersoSolutions/CordovaClipboard

This des not create errors on building, seems to be version 0.1.0 
It seems to work now!
