### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined when passing image server path 

### ISSUE THREAD

**Issue by billy124** [vstirbu/InstagramPlugin#64]
Hey guys,

Am passing in a path to the image on my server, however am getting this error :

 Object.Plugin.share (file:///android_asset/www/plugins/cordova-instagram-plugin/www/CDVInstagramPlugin.js:93:18)

I am using ionic, 

code

$cordovaInstagram.share('https://pathtomyimage.com/image.png').then(function () {
                //success
            }, function (err) {
               //fail
            });

**Comment by vstirbu** [comment]
Would this #29, in conjunction with [file transfer](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file-transfer/index.html#download) plugin fix your issue?

The rationale is to use as much as possible other plugins instead of turning this into something mega. Of course in the long term this flow can be bundled in this plugin.

**Comment by amurbelikov** [comment]
Hi, I have got "TypeError: Cannot read property 'slice' of undefined" in cordova Instagram plugin.
Can you help me now?

**Comment by muhzi4u** [comment]
@amurbelikov @billy124 Any one got the solution ?

**Comment by muhzi4u** [comment]
@vstirbu I have tried you suggestion .But getting the same error.
**Console Log**

![screen shot 2017-09-17 at 12 05 45 pm](https://user-images.githubusercontent.com/12408980/30518610-a8742ce6-9ba0-11e7-82e1-b8c0e934ae09.png)

**JS Code**
```
var url = encodeURI("http://image.tmdb.org/t/p/w500/Ap1HWHe4qGBCEPauaSw9UX1kQZB.jpg");
var filename = 'image.png';
var targetPath = cordova.file.externalRootDirectory + filename;
$cordovaFileTransfer.download(url, targetPath, {}, true).then(function(result) {
        var mywallpaper = result.toURL();
        console.log('Your download is completed', mywallpaper);
        window.resolveLocalFileSystemURL(mywallpaper, function(fileEntry) {
            fileEntry.file(function(file) {
                var reader = new FileReader(),
                    data = null;
                reader.onloadend = function(event) {
                    data = reader.result;
                    $cordovaInstagram.share(data, 'Sharing image on insta').then(function() {}, function(err) {
                        console.log(err);
                    });
                };
                reader.readAsDataURL(file)
            });
        });
    },
    function(error) {},
    function(progress) {
    });
```

**Comment by vstirbu** [comment]
It appears that the `data` that you provide to share function is undefined.

**Comment by muhzi4u** [comment]
@vstirbu Thank you very much.It is working now.Can i add this solution in to README.md file?

**Comment by vstirbu** [comment]
Yes, make a pull request with the working solution.
