### ISSUE TITLE
Share instagram on iPad

### ISSUE THREAD

**Issue by dmarcos89** [vstirbu/InstagramPlugin#67]
Hi, i am developing a ionic app and your plugin seems great!
I installed instagram on my iPad, and when attempting to share a photo, this is what i get on Xcode:

`
2016-08-08 12:36:06.231 HelloCordova[1188:339409] THREAD WARNING: ['Instagram'] took '1335.712158' ms. Plugin should use a background thread.
`

Any idea?

Thanks in advance for your help.

**Comment by vstirbu** [comment]
Any info about the iPad version and the image size?

**Comment by dmarcos89** [comment]
> For image size i am using a random 100 x 100 (maybe its too small?).

Using an ipad 2 wifi, jan 2013.
ios 9.3.4

Thanks again!

**Comment by rodrigograca31** [comment]
Closing this issue as it's not relevant anymore.
