### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by roysG** [vstirbu/InstagramPlugin#69]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIDocumentInteractionController has gone away prematurely!'
*** First throw call stack:
(0x18278ae38 0x181deff80 0x18278ad08 0x183110124 0x187f76c20 0x1881aa268 0x187c31854 0x187c34a4c 0x187a04fd8 0x187910014 0x18790fb10 0x18790f998 0x18527da20 0x1002c9a3c 0x1002cf4e4 0x182740dd8 0x18273ec40 0x182668d10 0x183f50088 0x18793df70 0x10005272c 0x1822068b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vstirbu** [comment]
The PR does not have enough information to identify what went wrong. Can you replicate the behaviour in the sample [app](https://github.com/vstirbu/instagramplugin-example)?

**Comment by roysG** [comment]
Never mind i remove and install again and not it works :)
