### ISSUE TITLE
Install/Use issues with Ionic

### ISSUE THREAD

**Issue by arturalkaim** [vstirbu/InstagramPlugin#73]
Hello, I'm developing an app using Ionic 2.

I tried to install this plugin with:
`ionic plugin add cordova-instagram-plugin`
`ionic plugin add https://github.com/vstirbu/InstagramPlugin.git`
`cordova plugin add cordova-instagram-plugin`

And I always get the following error
`'"/Users/mypc/myproject/node_modules/ionic-native/dist/index"' has no exported member 'Instagram'.`
On
`import { Facebook, SocialSharing, TwitterConnect, Instagram} from 'ionic-native';`

Any help on this?
Best Regards

**Comment by vstirbu** [comment]
The error suggests that the problems is on the `ionic-native` side. Do you have an up to date ionic-native. Seems that they have added support [recently](https://github.com/driftyco/ionic-native/pull/453).

**Comment by arturalkaim** [comment]
Thanks! That fixed!
Does this plugin allows sign in with instagram?

**Comment by vstirbu** [comment]
No, the functionality is limited to sharing using the native app.
