### ISSUE TITLE
Just Open Instagram app

### ISSUE THREAD

**Issue by arturalkaim** [vstirbu/InstagramPlugin#74]
Hi,

I'm using this plugin to allow my users to post to instagram. 
But sometimes I do not have a predefined content for them to post.
They first have to pick the file from the gallery and then are redirected to the Instagram's "file picker" page and see all their pics again.

Is there any way to just open instagram and they can choose the pic there?

Thanks,
Best regards

**Comment by arturalkaim** [comment]
Sometimes the user needs to post something that was already in the gallery and it feels weird if he has too see the gallery twice.

**Comment by CelsoSantos** [comment]
I have to agree with @arturalkaim.

It may not be the main purpose of the plugin but it is a possibility that should be provided since instagram also allows that

**Comment by micheltobon** [comment]
@arturalkaim in that case what you can do is in the camera plugin, to set the source of the image to be the GALLERY, that way the user will be able to select something that he already had before and post it that way but the image will already be sent to instagram

**Comment by arturalkaim** [comment]
@micheltobon that is what I'm doing...
I just wanted to choose it within Instagram

**Comment by ajayV1992** [comment]
@arturalkaim did you find the solution.

**Comment by rodrigograca31** [comment]
There's cordova plugins to launch an app.... You just need to provide the Instagram package name...

**Comment by ajayV1992** [comment]
Is there any solution for launching the instagram app after the image is selected instead of picking the instagram app from share to picker.
It was working before "Fixes for Android N restrictions" but after that it started showing other apps to share.

**Comment by rodrigograca31** [comment]
Closing this issue as it's not relevant to this project.

Will leave some useful links here:
- https://ionicframework.com/docs/native/app-launcher
- https://github.com/nchutchind/cordova-plugin-app-launcher
- https://forum.ionicframework.com/t/ionic-opening-external-app/77932/3
