### ISSUE TITLE
Direct instagram launch

### ISSUE THREAD

**Issue by ajay92x** [vstirbu/InstagramPlugin#79]
After the image is selected launch the instagram app instead of picking the instagram app from share to picker.

**Comment by vstirbu** [comment]
Which platform are you referring to?

If iOS, then there is another app that registered that it can handle the same media as Instagram. You cannot bypass that selection.

**Comment by ajayV1992** [comment]
In Samsung A5 (marshmallow), before the update of this plugin it was working but after the update it showing Instagram picker instead to launching the Instagram app to share.

**Comment by gildebrand** [comment]
Use the `shareAsset` method instead. This works! However, you have to save the image to the local photo library and pass the path to the image!

**Comment by ajayV1992** [comment]
But plugin is showing shareAssest is for iOS only

**Comment by rodrigograca31** [comment]
Closing in favor of #93
