### ISSUE TITLE
Unable to share Video via instagram

### ISSUE THREAD

**Issue by gopalaiahvinay** [vstirbu/InstagramPlugin#80]
Instagram.shareAsset(function(result) {
                  console.log('Instagram.shareAsset success: ' + result);
                }, function(e) {
                  console.log('Instagram.shareAsset error: ' + e);
                }, localFileUrl);
              }, function() {
                // error
   });

I am unable to share a video to instagram, I am passing the local file url as a parameter. 
I am getting an error saying: 'Invalid Action'. 
In documentation you say we can use PHAssets to get assets identifier. But what do we have to use in android to get an asset identifier? 

Please point me to an appropriate documentation where it shows how to share video to instagram on android.

**Comment by vstirbu** [comment]
this method is iOS specific. follow #49 to see what the outcome will be for android.
