### ISSUE TITLE
Caption not copying with ios11

### ISSUE THREAD

**Issue by albertleao** [vstirbu/InstagramPlugin#87]
When testing, I tried also pasting into the 'Notes' app and it seems to paste a text file that is only a few bytes large.

**Comment by albertleao** [comment]
Alright I figured it out. It has to do with the clipboard plugin that comes with this plugin. The issue and fix are found here: 
https://github.com/VersoSolutions/CordovaClipboard/issues/26

With all the changes to the clipboard on iOS, might I suggest the removal of any dependencies and leave the clipboard portion to the user itself?

**Comment by vstirbu** [comment]
Yep, removing the caption functionality is one option although a bit radical, considering how common is for the users of this plugin. It is further complicated as the clipboard plugin is not actually maintained.

Is your fork backwards compatible? Can you make a PR?

Thanks

**Comment by albertleao** [comment]
It's working on ios11, I'm going to test it on ios 9 and 10 tonight and will let you know.

**Comment by albertleao** [comment]
https://github.com/Visigo/CordovaClipboard/pull/2

**Comment by mreis92** [comment]
Hi there, I have encountered this problem as well. Is there any known workaround I can implement for this?
