### ISSUE TITLE
add reference to config.xml Ionic 2

### ISSUE THREAD

**Issue by lianesten** [vstirbu/InstagramPlugin#88]
Improvement:

Hello!

When I use another cordova plugin, their reference is set it automatically in the file config.xml. This no happen adding the instagram plugin:

`cordova plugin add cordova-instagram-plugin`

so, when i run the project in another machine for example, the instagram plugin never will be install because there is not any reference from config.xml file.

the line in config.xml file must be:

`<plugin name="cordova-instagram-plugin" spec="~0.5.5" />`

is this way correct?
am I doing something wrong?

**Comment by vstirbu** [comment]
If you run add this plugin in a project and want to share it on another machine (e.g. via git) you need to do the following:

```
cordova plugin add cordova-instagram-plugin --save
```

**Comment by lianesten** [comment]
Thank u so much @vstirbu worked perfect!!
