### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by vinceharmon** [vstirbu/InstagramPlugin#89]
I'm running the command to add the plugin into my project
**cordova plugin add cordova-instagram-plugin --save** 

The plugin installation fails when it's trying to pull in the depend project: **Visigo/CordovaClipboard**

with error:
**Error: Failed to fetch plugin https://github.com/Visigo/CordovaClipboard.git via registry.**

I have tried this a number of times with the same result.

I'm using **Cordova 7.0.1**.

Would it be possible to address the CordovaClipboard repository so it can be loaded?

Regards,
Vince

**Comment by rodrigograca31** [comment]
@vinceharmon are you still facing this problem? If not please close the issue

**Comment by rodrigograca31** [comment]
Seems to be related to the clipboard plugin which I just changed to `cordova-clipboard`, see #104

This should be fixed. Closing.
