### ISSUE TITLE
Plugin doesn't work on iPhone X

### ISSUE THREAD

**Issue by zulfu** [vstirbu/InstagramPlugin#92]
I tried on iPhone X, 5s, 8, 7 it doesnt work on Instagram 27.0 version. Image area is empty.

![whatsapp image 2018-01-03 at 22 26 56](https://user-images.githubusercontent.com/4500888/34541615-f72c3f42-f0e9-11e7-84ed-cd2e0e86669f.jpeg)

**Comment by rodrigograca31** [comment]
Old issue. Not relevant anymore.
