### ISSUE TITLE
Instagram composer not returning to app after img is shared

### ISSUE THREAD

**Issue by rolinger** [vstirbu/InstagramPlugin#94]
Testing on Android and I finally got this working.  But the only way it seems to exit Instagram to back to my app is for the user to physically close Instagram or return my app to the foreground. And when I do that the `err` callback is registering the basic "Not Shared" error so my app is not able to properly track if the post was successful or not.  It IS posting though...just not getting the proper response back.

How is the user supposed to cleanly exit instagram after the post or how am I able to force returning to my own app properly?

**Comment by vstirbu** [comment]
Instagram app behaviour changed over time on the topic of returning to the activity sharing calling app. The plugin just calls the [API](https://www.instagram.com/developer/mobile-sharing/android-intents/) as specified by Instagram. No control on what happens next.

**Comment by ensemblebd** [comment]
Just to comment, several apps do this. 
The "reshare" apps, which launch Instagram with the image (as this one does), and upon completion it returns back. 

So with some effort I think this is do-able, to research how those apps do it, and implement in the cordova plugin for both ios & android.
It's very important to my app, so I may share results if I can arrive upon the solution. 

Not trying to necro an old thread.... But everything in cordova / meteor is 2 to 6 years old anyway. Impossible to avoid it.

**Comment by rodrigograca31** [comment]
👍🏻
